package com.widevision.numeral_concidepieces.util;

import com.widevision.numeral_concidepieces.R;

/**
 * Created by rocks on 10/08/16.
 */
public class Constant {
    public static int playStore_icon[] = {R.drawable.addtotad_playstore_icon, R.drawable.ascendo_descendo_playstore_icon, R.drawable.big_small_number_quest_playstore_icon, R.drawable.divide_funride_playstore_icon, R.drawable.fruit_hunt_playstore_icon, R.drawable.geometry_junction_playstore_icon, R.drawable.kids_number_fun_playstore_icon, R.drawable.livo_hunt_playstore_icon, R.drawable.minus_zone_playstore_icon, R.drawable.more_less_number_sense_playstore_icon, R.drawable.multiplico_order_playstore_icon, R.drawable.multiply_babyfly_playstore_icon, R.drawable.numbers_play_playstore_icon,  R.drawable.numeral_draggle_drop_playstore_icon, R.drawable.numeral_riddles_playstore_icon, R.drawable.numero_order_playstore_icon, R.drawable.objecto_count_playstore_icon, R.drawable.odd_even_ordo_playstore_icon, R.drawable.shapes_hunt_playstore_icon, R.drawable.stationary_hunt_playstore_icon, R.drawable.target_hunt_playstore_icon, R.drawable.tot_up_ten_playstore_icon, R.drawable.vegge_hunt_playstore_icon, R.drawable.weight_it_up_playstore_icon};
    public static int splash[] = {R.drawable.add_for_tad_splash, R.drawable.ascendo_descendo_splash, R.drawable.big_small_number_quest_splash, R.drawable.divide_splash, R.drawable.fruit_hunt_splash, R.drawable.geometry_junction_splash, R.drawable.kids_number_fun_splash, R.drawable.livo_hunt_splash, R.drawable.minus_splash, R.drawable.more_less_no_sence_splash, R.drawable.multiplico_order_splash, R.drawable.multiply_babyfly_splash, R.drawable.number_ply_splash,  R.drawable.numeral_draggle_drop_splash, R.drawable.numeral_riddle_splash, R.drawable.numero_order_splash, R.drawable.objecto_count_splash, R.drawable.odd_even_ordo_splash, R.drawable.shapes_hunt_splash, R.drawable.stationary_hunt_splash, R.drawable.target_hunt_splash, R.drawable.tot_up_ten_splash, R.drawable.vegge_hunt_splash, R.drawable.weigh_it_up_splash};
    public static String packagename[] = {"com.widevision.add_forTad", "com.widevision.ascendo_descendo", "com.widevision.big_small_number","com.widevision.divide_funride","com.widevision.fruit_hunt","com.widevision.geometry_junction","com.widevision.kids_number_fun","com.widevision.livo_hunt","com.widevision.minus_zone", "com.widevision.more_less_number_sence","com.widevision.multipilco", "com.wideVision.multiply_babyfly", "com.widevision.numbers_play", "com.widevision.numeral_daggledrop", "com.widevision.numeral_riddles", "com.widevision.numeroorder",  "com.widevision.object_count","com.widevision.oddevenordo",    "com.widevision.shapes_hunt", "com.widevision.stationary_hunt", "com.widevision.target_hunt", "com.widevision.tot_up_ten","com.widevision.veggie_hunt",  "com.widevision.weight_it_up"};}